version: '3.7'

services:
  chatbot:
    build: .
    ports:
      - '8080:8080'
    restart: always
  test:
    build: .
    environment:
      - FLASK_APP=source/bot.py
      - FLASK_ENV=development
    ports:
      - '8080:8080'
    volumes:
       - .:/app
    command: bash -c "flask run -p 8080 -h 0.0.0.0"


